data:
  name: configParser
  server:
    ip: 127.0.0.1
    port: 25565
  players:
    notch:
      ip: 192.168.0.1
      money: 29445
      friends:
      - player1
      - player2
      - player3
      items:
    md_5:
      ip: 192.168.0.2
      money: 94
      friends:
      - player1
      - player2
      - player3
      items:
    dinnerbone:
      ip: 192.168.0.3
      money: 262
      friends:
      - player1
      - player2
      - player3
      items:
  points:
    notch: 39
    md_5: 92
    dinnerbone: 45

